security:
    providers:
        in_memory:
            memory: ~
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        secured_area:
              anonymous: ~
              oauth:
                  resource_owners:
                      facebook:           "/login/check-facebook"
                  login_path:        /login
                  use_forward:       false
                  failure_path:      /login
                  oauth_user_provider:
                      service: hwi_oauth.user.provider


        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~



    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^, roles: ROLE_USER }

